theme: jekyll-theme-minimal
# theme: jekyll-swiss
# theme_color: white
#
title: Gerenciamento de projetos
description: Página da disciplina de Gerenciamento de projetos
show_downloads: false
lang: pt-BR
